# Generated by Django 3.1.4 on 2021-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lessonid', models.AutoField(help_text='課程ID編號，自動產生', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='課程名稱', max_length=45)),
                ('lessontype', models.CharField(help_text='課程種類', max_length=45)),
                ('auth', models.IntegerField(default=0, help_text='建立者')),
                ('situation', models.CharField(help_text='實體、線上或兩者皆有', max_length=15)),
                ('verify', models.BooleanField(default=False)),
                ('annouce_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('lessoninfo', models.CharField(max_length=300)),
                ('certificate', models.BooleanField(default=False)),
                ('address', models.CharField(default='online mode', max_length=300)),
            ],
            options={
                'db_table': 'lesson',
                'managed': False,
            },
        ),
    ]
