# Generated by Django 3.1.4 on 2021-06-03 15:36

from django.db import migrations, models
import django.db.models.deletion
import lesson_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentlist',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('student_id', models.IntegerField(verbose_name='student_id')),
                ('first_name', models.CharField(max_length=150, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last_name')),
                ('lesson_situation', models.CharField(max_length=150, null=True, verbose_name='lesson_situation')),
                ('agree', models.BooleanField(default=True, verbose_name='agree')),
                ('join_reason', models.CharField(max_length=300, null=True, verbose_name='join_reason')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
            options={
                'db_table': 'lesson_studentlist',
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('cover', models.BooleanField(default=False, verbose_name='cover')),
                ('textbook', models.BooleanField(default=False, verbose_name='textbook')),
                ('media_type', models.IntegerField(help_text='file:0 picture:1 vided:2', verbose_name='media_type')),
                ('file', models.FileField(null=True, upload_to=lesson_app.models.path_return, verbose_name='file')),
                ('image', models.ImageField(null=True, upload_to=lesson_app.models.path_return, verbose_name='image')),
                ('filename', models.CharField(max_length=150, verbose_name='filename')),
                ('open_access', models.BooleanField(default=True, verbose_name='open_access')),
                ('only_for_members', models.BooleanField(default=True, verbose_name='only_for_members')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
            options={
                'db_table': 'lesson_multimedia',
            },
        ),
        migrations.CreateModel(
            name='LessonTable',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('ch', models.IntegerField(default=0)),
                ('sb', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=150, null=True)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
            options={
                'db_table': 'lesson_table',
            },
        ),
        migrations.CreateModel(
            name='LessonRelatedMedia',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_id', models.IntegerField()),
                ('media_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.multimedia')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lessontable')),
            ],
            options={
                'db_table': 'lesson_related_media',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmit',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('submitinfo', models.CharField(max_length=300, null=True, verbose_name='submitinfo')),
                ('attach_file_exist', models.BooleanField(default=False, verbose_name='attach_file_exist')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
                ('lessontable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lessontable', verbose_name='lesson_table_id')),
            ],
            options={
                'db_table': 'homeworksubmit',
            },
        ),
        migrations.CreateModel(
            name='HomeworkFileTable',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('attach_or_submit', models.CharField(default='attach', max_length=10, verbose_name='attach_or_submit')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='file')),
                ('lesson_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
                ('lessontable_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lessontable', verbose_name='lesson_table_id')),
            ],
            options={
                'db_table': 'homeworkfiletable',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('homeworkinfo', models.CharField(max_length=300, null=True, verbose_name='homeworkinfo')),
                ('attach_file_exist', models.BooleanField(default=False, verbose_name='attach_file_exist')),
                ('start_time', models.DateField(default='1900-01-01', verbose_name='start_time')),
                ('finish_time', models.DateField(default='9999-12-31', verbose_name='finish_time')),
                ('turn_it_available', models.BooleanField(default=False, verbose_name='turn_it_available')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
                ('lessontable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lessontable', verbose_name='lesson_table_id')),
            ],
            options={
                'db_table': 'homework',
            },
        ),
    ]
