# Generated by Django 3.1.4 on 2021-06-17 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0003_homeworkfiletable_homeworksubmit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmit',
            name='homework_id',
            field=models.ForeignKey(default=-9, on_delete=django.db.models.deletion.CASCADE, to='lesson_app.homework', verbose_name='homework_id'),
        ),
    ]
