# Generated by Django 3.1.4 on 2021-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0005_auto_20210622_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkattachfile',
            name='open_access',
            field=models.BooleanField(default=False, verbose_name='open_access'),
        ),
    ]
