# Generated by Django 3.1.4 on 2021-07-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0007_homeworkattachfile_only_for_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='external_source',
            field=models.CharField(max_length=500, null=True, verbose_name='external_source'),
        ),
    ]
