# Generated by Django 3.1.4 on 2021-08-26 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0011_homeworksubmit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmit',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='submit_time'),
            preserve_default=False,
        ),
    ]
