# Generated by Django 3.1.4 on 2021-03-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lessonid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('lessontype', models.CharField(max_length=45)),
                ('auth', models.IntegerField()),
                ('situation', models.IntegerField()),
                ('annouce_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('lessoninfo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'lesson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='id')),
                ('first_name', models.CharField(max_length=150, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last_name')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('media_type', models.IntegerField(verbose_name='media_type')),
                ('filename', models.CharField(max_length=150, verbose_name='filename')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
        ),
    ]
