# Generated by Django 3.1.4 on 2021-04-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lessonid', models.AutoField(help_text='課程ID編號，自動產生', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='課程名稱', max_length=45)),
                ('lessontype', models.CharField(help_text='課程種類', max_length=45)),
                ('auth', models.IntegerField(default=0, help_text='建立者')),
                ('situation', models.CharField(help_text='實體、線上或兩者皆有', max_length=15)),
                ('statue', models.BooleanField(default=False)),
                ('annouce_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('lessoninfo', models.CharField(max_length=300)),
                ('certificate', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lesson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentlist',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('student_id', models.IntegerField(verbose_name='student_id')),
                ('first_name', models.CharField(max_length=150, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last_name')),
                ('lesson_situation', models.CharField(max_length=150, null=True, verbose_name='lesson_situation')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('cover', models.BooleanField(default=False, verbose_name='cover')),
                ('media_type', models.IntegerField(help_text='file:0 picture:1 vided:2', verbose_name='media_type')),
                ('file', models.FileField(null=True, upload_to='fileinfo/lesson_info', verbose_name='file')),
                ('image', models.ImageField(null=True, upload_to='fileinfo/lesson_info', verbose_name='image')),
                ('filename', models.CharField(max_length=150, verbose_name='filename')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTable',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('ch', models.IntegerField(default=0)),
                ('sb', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=150, null=True)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
            options={
                'db_table': 'lesson_table',
            },
        ),
    ]
