# Generated by Django 3.1.4 on 2021-02-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lseeonid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('lessontype', models.CharField(max_length=45)),
                ('auth', models.IntegerField()),
                ('situation', models.IntegerField()),
                ('annouce_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('lessoninfo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'lesson',
                'managed': False,
            },
        ),
    ]
