# Generated by Django 3.1.4 on 2021-03-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0002_multimedia_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='file',
            field=models.FileField(default=False, upload_to='fileinfo/lesson_info', verbose_name='file'),
        ),
    ]
