# Generated by Django 3.1.4 on 2021-06-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0002_homework_homeworkfiletable_homeworksubmit_lessonrelatedmedia_lessontable_multimedia_studentlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkfiletable',
            name='homeworksubmit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson_app.homeworksubmit', verbose_name='homeworksubmit_id'),
        ),
    ]
