# Generated by Django 3.1.4 on 2021-03-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0002_studentlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='lesson_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id'),
        ),
    ]
