# Generated by Django 3.1.4 on 2021-03-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0003_auto_20210304_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField(verbose_name='id')),
                ('media_type', models.IntegerField(verbose_name='media_type')),
                ('lesson_id', models.IntegerField(verbose_name='lesson_id')),
                ('filename', models.CharField(max_length=150, verbose_name='filename')),
            ],
        ),
    ]
