# Generated by Django 3.1.4 on 2021-03-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0004_auto_20210315_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'managed': True},
        ),
    ]
