# Generated by Django 3.1.4 on 2021-03-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0004_multimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='lesson_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id'),
        ),
    ]
