# Generated by Django 3.1.4 on 2021-06-22 15:24

from django.db import migrations, models
import django.db.models.deletion
import lesson_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0004_homeworksubmit_homework_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkfiletable',
            name='attach_or_submit',
        ),
        migrations.CreateModel(
            name='HomeworkAttachFile',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('file', models.FileField(null=True, upload_to=lesson_app.models.homework_file_path_return, verbose_name='file')),
                ('homeworkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.homework', verbose_name='homework_id')),
            ],
            options={
                'db_table': 'homework_attach_file',
            },
        ),
    ]
