# Generated by Django 3.1.4 on 2021-03-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0005_auto_20210316_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='LessonTable',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('ch', models.IntegerField(default=0)),
                ('sb', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=150, null=True)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
            options={
                'db_table': 'lesson_table',
            },
        ),
    ]
