# Generated by Django 3.1.4 on 2021-03-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0005_auto_20210311_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='id',
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='media_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
