# Generated by Django 3.1.4 on 2021-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0005_auto_20210316_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.IntegerField()),
            ],
            options={
                'db_table': 'lesson_table',
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'managed': False},
        ),
    ]
