# Generated by Django 3.1.4 on 2021-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0006_auto_20210408_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='agree',
            field=models.BooleanField(default=True, verbose_name='agree'),
        ),
    ]
