# Generated by Django 3.1.4 on 2021-06-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0006_homeworkattachfile_open_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkattachfile',
            name='only_for_members',
            field=models.BooleanField(default=False, verbose_name='only_for_members'),
        ),
    ]
