# Generated by Django 3.1.4 on 2021-03-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0006_auto_20210325_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='image',
            field=models.ImageField(null=True, upload_to='fileinfo/lesson_info', verbose_name='image'),
        ),
    ]
