# Generated by Django 3.1.4 on 2021-03-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0007_multimedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='media_type',
            field=models.IntegerField(help_text='file:0 picture:1 vided:2', verbose_name='media_type'),
        ),
    ]
