# Generated by Django 3.1.4 on 2021-04-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0008_studentlist_join_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmit',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('lessontable_id', models.IntegerField(null=True, verbose_name='lessontable_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('submitinfo', models.CharField(max_length=300, null=True, verbose_name='submitinfo')),
                ('attach_file_exist', models.BooleanField(default=False, verbose_name='attach_file_exist')),
                ('attach_file', models.FileField(null=True, upload_to='homework_data', verbose_name='attach_file')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
            options={
                'db_table': 'homeworksubmit',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('lessontable_id', models.IntegerField(null=True, verbose_name='lessontable_id')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('homeworkinfo', models.CharField(max_length=300, null=True, verbose_name='homeworkinfo')),
                ('attach_file_exist', models.BooleanField(default=False, verbose_name='attach_file_exist')),
                ('attach_file', models.FileField(null=True, upload_to='homework_data', verbose_name='attach_file')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
            options={
                'db_table': 'homework',
            },
        ),
    ]
