# Generated by Django 3.1.4 on 2021-04-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0008_auto_20210329_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='lesson_situation',
            field=models.CharField(max_length=150, null=True, verbose_name='lesson_situation'),
        ),
    ]
