# Generated by Django 3.1.4 on 2021-08-09 09:41

from django.db import migrations, models
import lesson_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0008_multimedia_external_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkfiletable',
            name='open_access',
            field=models.BooleanField(default=False, verbose_name='open_access'),
        ),
        migrations.AlterField(
            model_name='homeworkfiletable',
            name='file',
            field=models.FileField(null=True, upload_to=lesson_app.models.homework_submit_file_path_return, verbose_name='file'),
        ),
    ]
