# Generated by Django 3.1.4 on 2021-08-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0009_auto_20210809_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkfiletable',
            name='only_for_members',
            field=models.BooleanField(default=False, verbose_name='only_for_members'),
        ),
    ]
