# Generated by Django 3.1.4 on 2021-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0009_homework_homeworksubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='finish_time',
            field=models.DateField(default='9999-12-31', verbose_name='finish_time'),
        ),
        migrations.AddField(
            model_name='homework',
            name='start_time',
            field=models.DateField(default='1900-01-01', verbose_name='start_time'),
        ),
        migrations.AddField(
            model_name='homework',
            name='turn_it_available',
            field=models.BooleanField(default=False, verbose_name='turn_it_available'),
        ),
    ]
