# Generated by Django 3.1.4 on 2021-04-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0010_auto_20210420_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkFileTable',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
            ],
            options={
                'db_table': 'homeworkfiletable',
            },
        ),
    ]
