# Generated by Django 3.1.4 on 2021-08-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0010_homeworkfiletable_only_for_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmit',
            name='score',
            field=models.IntegerField(null=True, verbose_name='score'),
        ),
    ]
