# Generated by Django 3.1.4 on 2021-05-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0012_auto_20210423_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRelatedMedia',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_id', models.IntegerField()),
                ('media_id', models.IntegerField()),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lessontable')),
            ],
            options={
                'db_table': 'lesson_related_media',
            },
        ),
    ]
