# Generated by Django 3.1.4 on 2021-05-05 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0013_lessonrelatedmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrelatedmedia',
            name='media_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.multimedia'),
        ),
    ]
