# Generated by Django 3.1.4 on 2021-05-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0014_auto_20210505_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrelatedmedia',
            name='media_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.multimedia'),
        ),
    ]
