# Generated by Django 3.1.4 on 2021-05-11 16:23

from django.db import migrations, models
import lesson_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0015_auto_20210505_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='textbook',
            field=models.BooleanField(default=False, verbose_name='textbook'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='file',
            field=models.FileField(null=True, upload_to=lesson_app.models.path_return, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='image',
            field=models.ImageField(null=True, upload_to=lesson_app.models.path_return, verbose_name='image'),
        ),
    ]
