# Generated by Django 3.1.4 on 2021-05-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0016_auto_20210511_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='open_access',
            field=models.BooleanField(default=True, verbose_name='open_access'),
        ),
    ]
