# Generated by Django 3.1.4 on 2022-02-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson_app', '0012_homeworksubmit_submit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rollcall',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('sign_in_time', models.DateTimeField(verbose_name='sign_in_time')),
                ('lessontableid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lessontable', verbose_name='lessontable_id')),
            ],
            options={
                'db_table': 'rollcall',
            },
        ),
    ]
